module.exports = function () {
  return {
    products: [
      { id: 1,
        name: "Demon Blood Armor",
        category: "Axe",
        description: "Тяжелая броня, скованная в крови мертвых богов тарнийцев.",
        price: 3.96,
        image: 'assets/images/items/axe-1.png'
      },
      { id: 2,
        name: "Corruptor",
        category: "Axe",
        description: "Этот проклятый топор должен часто вкушать плоть, а иначе Axe покроется ужасающей сыпью, от которой не спасут целебные мази и порошки.",
        price: 16.85,
        image: 'assets/images/items/axe-2.png'
      },
      { id: 3,
        name: "Genuine Molten Claw",
        category: "Axe",
        description: "Торопясь поскорее расправиться со своими врагами, Axe ворвался в кузницу в поисках подходящих доспехов. Он нашел эту удобную броню, которую выковали совсем недавно. Включает в себя визуальный эффект.",
        price: 346.76,
        image: 'assets/images/items/axe-3.png'
      },
      { id: 4,
        name: "Helm of the Shattered Vanguard",
        category: "Axe",
        description: "Armor of the Shattered Vanguard",
        price: 49.74,
        image: 'assets/images/items/axe-4.png'
      },
      { id: 5,
        name: "Mantle of the Glacial Magnolia",
        category: "Crystal Maiden",
        description: "Glacial Magnolia",
        price: 3.15,
        image: 'assets/images/items/cm-1.png'
      },
      { id: 6,
        name: "Yulsaria's Glacier",
        category: "Crystal Maiden",
        description: "В холодных землях севера то, что стало легендой, до сих пор можно найти во льдах.",
        price: 154.87,
        image: 'assets/images/items/cm-2.png'
      },
      { id: 7,
        name: "Inscribed White Sentry",
        category: "Crystal Maiden",
        description: "Создание оберега — это своего рода обряд посвящения для молодого создателя магических предметов.",
        price: 779.97,
        image: 'assets/images/items/cm-3.png'
      },
      { id: 8,
        name: "Inscribed Winter Solstice Fashion",
        category: "Crystal Maiden",
        description: "Шарф с мехом арктических клыкастых лисиц поможет согреться даже в самую студеную зимнюю пору.",
        price: 250,
        image: 'assets/images/items/cm-4.png'
      },
      { id: 9,
        name: "Blood Shard",
        category: "Wraith King",
        description: "В исключительных случаях Wraith King может оценить даже не костяную вещь.",
        price: 59,
        image: 'assets/images/items/wk-1.png'
      },
      { id: 10,
        name: "Pauldron of the Dreadborn Regent",
        category: "Wraith King",
        description: "С точки зрения короля Остариона души его сторонников, отдавших жизни для ритуалов Ночи призраков, были просто данью.",
        price: 5.96,
        image: 'assets/images/items/wk-2.png'
      },
      { id: 11,
        name: "Cloak of the Haunted Lord",
        category: "Wraith King",
        description: "Haunted Lord",
        price: 100,
        image: 'assets/images/items/wk-3.png'
      },
      { id: 12,
        name: "Kabuto of the Dreadborn Regent",
        category: "Wraith King",
        description: "С точки зрения короля Остариона души его сторонников, отдавших жизни для ритуалов Ночи призраков, были просто данью.",
        price: 0.9,
        image: 'assets/images/items/wk-4.png'
      },
      { id: 13,
        name: "Coffin of the Jiang Shi's Revenge",
        category: "Lich",
        description: "Если мятежники придут снова, Этриан будет готов.",
        price: 2.33,
        image: 'assets/images/items/lich-1.png'
      },
      { id: 14,
        name: "Cage of Forbidden Knowledge",
        category: "Lich",
        description: "Пока завистливые мятежники связывали Этриана, они приковали его магическую книгу к его спине.",
        price: 0.94,
        image: 'assets/images/items/lich-2.png'
      },
      { id: 15,
        name: "Necklace of the Jiang Shi's Revenge",
        category: "Lich",
        description: "Если мятежники придут снова, Этриан будет готов.",
        price: 1,
        image: 'assets/images/items/lich-3.png'
      },
      { id: 16,
        name: "Robe of the Jiang Shi's Revenge",
        category: "Lich",
        description: "Если мятежники придут снова, Этриан будет готов.",
        price: 3,
        image: 'assets/images/items/lich-4.png'
      },
      { id: 17,
        name: "Helm of the Infernal Rambler",
        category: "Lion",
        description: "Прежде чем Lion по настоянию семьи устремился к званию Великого магистра демонологии и задолго до того, как он достиг этого титула и избрал темный путь.",
        price: 2.31,
        image: 'assets/images/items/lion-1.png'
      },
      { id: 18,
        name: "Mantle of Hell's Ambassador",
        category: "Lion",
        description: "Эта мантия — знак почтения народа демонов, указывающий на высокие полномочия адского сановника.",
        price: 2.79,
        image: 'assets/images/items/lion-2.png'
      },
      { id: 19,
        name: "Scepter of the Infernal Rambler",
        category: "Lion",
        description: "Прежде чем Lion по настоянию семьи устремился к званию Великого магистра демонологии и задолго до того, как он достиг этого титула и избрал темный путь.",
        price: 0.77,
        image: 'assets/images/items/lion-3.png'
      },
      { id: 20,
        name: "Corrupted Abyssal Hellclaw",
        category: "Lion",
        description: "Lion по настоянию отрастил себе странной формы палец.",
        price: 29,
        image: 'assets/images/items/lion-4.png'
      },
      { id: 21,
        name: "Headpiece of the Andestian Sentinel",
        category: "Slardar",
        description: "The Andestian Sentinel",
        price: 43.9,
        image: 'assets/images/items/sladar-1.png'
      },
      { id: 22,
        name: "Mantle of the Andestian Sentinel",
        category: "Slardar",
        description: "The Andestian Sentinel",
        price: 48.8,
        image: 'assets/images/items/sladar-2.png'
      },
      { id: 23,
        name: "Trident of the Sea Stalker",
        category: "Slardar",
        description: "Трезубец, проклятый сонмом морских богов и заточённый в глубины Кораллового разлома на тысячелетия.",
        price: 2.86,
        image: 'assets/images/items/sladar-3.png'
      },
      { id: 24,
        name: "Bracers of the Andestian Sentinel",
        category: "Slardar",
        description: "The Andestian Sentinel",
        price: 18.94,
        image: 'assets/images/items/sladar-4.png'
      },
      { id: 25,
        name: "Helm of the Mistral Fiend",
        category: "Abaddon",
        description: "Включает в себя иконки способностей.",
        price: 2.62,
        image: 'assets/images/items/abaddon-1.png'
      },
      { id: 26,
        name: "Steed of the Brinebred Cavalier",
        category: "Abaddon",
        description: "The Brinebred Cavalier",
        price: 1.31,
        image: 'assets/images/items/abaddon-2.png'
      },
      { id: 27,
        name: "Mistblade",
        category: "Abaddon",
        description: "Выкован в Фонтане Аверно и наполнен темной жаждой.",
        price: 3.8,
        image: 'assets/images/items/abaddon-3.png'
      },
      { id: 28,
        name: "Frozen Iceshard",
        category: "Abaddon",
        description: "Черный туман Аверно может поведать секреты правления, ведения боя и завоевания. Неудивительно, что даже бессмертные демоны Ада ненавидят и опасаются Abaddon в равной мере.",
        price: 5,
        image: 'assets/images/items/abaddon-4.png'
      },
      { id: 29,
        name: "Abyssal Scourge",
        category: "Abyssal Underlord",
        description: "Когда придёт Орда бездны, во главе её непременно будет стоять Врогрош, жаждущий подчинить своей злой воле новые земли.",
        price: 9.31,
        image: 'assets/images/items/au-1.png'
      },
      { id: 30,
        name: "Kopesh of the Convicts",
        category: "Alchemist",
        description: "The Convicts' Trophies.",
        price: 2.12,
        image: 'assets/images/items/alchemist-1.png'
      },
      { id: 31,
        name: "Helm of Big 'Un",
        category: "Alchemist",
        description: "The Convicts' Trophies.",
        price: 5.08,
        image: 'assets/images/items/alchemist-2.png'
      },
      { id: 32,
        name: "Inscribed Ogre's Caustic Steel Choppers",
        category: "Alchemist",
        description: "Хороши для перемешивания веществ, отличны для нарезки ужина!",
        price: 9.84,
        image: 'assets/images/items/alchemist-3.png'
      },
      { id: 33,
        name: "Inscribed Razzil's Midas Knuckles",
        category: "Alchemist",
        description: "Мидас с давних пор считался самым успешным алхимиком. Пытаясь уменьшить бремя войны, он разработал несколько видов перчаток.",
        price: 17,
        image: 'assets/images/items/alchemist-4.png'
      },
      { id: 34,
        name: "Plate of the Giant Hunter",
        category: "Bounty Hunter",
        description: "Giant Hunter.",
        price: 4.71,
        image: 'assets/images/items/bh-1.png'
      },
      { id: 35,
        name: "Armor of the Hunter's Glory",
        category: "Bounty Hunter",
        description: "Даже самые одарённые охотники могут лишь надеяться за всю жизнь заработать столько, сколько Гондар получает после одной охоты.",
        price: 3.91,
        image: 'assets/images/items/bh-2.png'
      },
      { id: 36,
        name: "Greater Twin Blade",
        category: "Bounty Hunter",
        description: "Воистину, умения Гондара — это искусство, и уважение с мастерством ему куда важнее, чем награда за чью-то голову, но любой его клиент наверняка знает, что благотворительностью охотник не занимается.",
        price: 17.46,
        image: 'assets/images/items/bh-3.png'
      },
      { id: 37,
        name: "Shuriken of the Hunter",
        category: "Bounty Hunter",
        description: "Hunter with No Name.",
        price: 0.5,
        image: 'assets/images/items/bh-4.png'
      },
      { id: 38,
        name: "Thirst of Eztzhok Blade",
        category: "Bloodseeker",
        description: "Повелители-близнецы осуждают Bloodseeker за ношение демонического оружия пред их взором. Но демонам не чужда жажда резни, и там, где кожу отделяют от плоти, крови хватит на всех.",
        price: 30.94,
        image: 'assets/images/items/bloodseeker-1.png'
      },
      { id: 39,
        name: "Cowl of the Blood Covenant",
        category: "Bloodseeker",
        description: "Тому, кто ведом взглядом Бескожих, не нужны глаза.",
        price: 1.56,
        image: 'assets/images/items/bloodseeker-2.png'
      },
      { id: 40,
        name: "Infused Helm of the Primeval Predator",
        category: "Bloodseeker",
        description: "В древней родословной охотников за кровью Стригвир лишь одно из зол, хотя никто из ныне живущих не может назвать его меньшим.",
        price: 30.19,
        image: 'assets/images/items/bloodseeker-3.png'
      },
      { id: 41,
        name: "Gauntlets of the Primeval Predator",
        category: "Bloodseeker",
        description: "В древней родословной охотников за кровью Стригвир лишь одно из зол, хотя никто из ныне живущих не может назвать его меньшим.",
        price: 3.52,
        image: 'assets/images/items/bloodseeker-4.png'
      },
      { id: 42,
        name: "Hellstrider",
        category: "Chaos Knight",
        description: "Где проезжает рыцарь, остается лишь хаос.",
        price: 4.99,
        image: 'assets/images/items/ch-1.png'
      },
      { id: 43,
        name: "Helm of Discord",
        category: "Chaos Knight",
        description: "Champion of Discord.",
        price: 1.99,
        image: 'assets/images/items/ch-2.png'
      },
      { id: 44,
        name: "Dark Ruin Gaze",
        category: "Chaos Knight",
        description: "Ходят слухи, что слепых кузнецов разрушенной цитадели посещают видения из миров за гранью понимания смертных.",
        price: 0.5,
        image: 'assets/images/items/ch-3.png'
      },
      { id: 45,
        name: "Hellstrider",
        category: "Chaos Knight",
        description: "Где проезжает рыцарь, остается лишь хаос.",
        price: 4.99,
        image: 'assets/images/items/ch-4.png'
      },
      { id: 46,
        name: "Shield of the Eldwurm Crest",
        category: "Dragon Knight",
        description: "Legacy of the Eldwurm Crest.",
        price: 4.17,
        image: 'assets/images/items/dk-1.png'
      },
      { id: 47,
        name: "Blade of the Fire Dragon",
        category: "Dragon Knight",
        description: "Fire Dragon of Doom.",
        price: 0.8,
        image: 'assets/images/items/dk-2.png'
      },
      { id: 48,
        name: "Cuirass of the Eldwurm Crest",
        category: "Dragon Knight",
        description: "Legacy of the Eldwurm Crest.",
        price: 8.81,
        image: 'assets/images/items/dk-3.png'
      },
      { id: 49,
        name: "Vambrace of the Blazing Superiority",
        category: "Dragon Knight",
        description: "The Blazing Superiority.",
        price: 0.5,
        image: 'assets/images/items/dk-4.png'
      },
      { id: 50,
        name: "Quiver of the Eldwurm's Touch",
        category: "Drow Ranger",
        description: "Eldwurm's Touch.",
        price: 0.83,
        image: 'assets/images/items/dr-1.png'
      },
      { id: 51,
        name: "Death Shadow Cowl",
        category: "Drow Ranger",
        description: "Death Shadow.",
        price: 0.5,
        image: 'assets/images/items/dr-2.png'
      },
      { id: 52,
        name: "Cape of the Winged Bolt",
        category: "Drow Ranger",
        description: "Guise of the Winged Bolt.",
        price: 1.62,
        image: 'assets/images/items/dr-3.png'
      },
      { id: 53,
        name: "Longbow of the Boreal Watch",
        category: "Drow Ranger",
        description: "Только те, кто приспособлен к морозу, смогут натянуть тетиву Тундры Уокер.",
        price: 0.56,
        image: 'assets/images/items/dr-4.png'
      },
      { id: 54,
        name: "Totem of the Crimson Beast",
        category: "Earthshaker",
        description: "Crimson Beast.",
        price: 1.55,
        image: 'assets/images/items/shaker-1.png'
      },
      { id: 55,
        name: "Helm of the Red Mountain",
        category: "Earthshaker",
        description: "Guardian of the Red Mountain.",
        price: 5.53,
        image: 'assets/images/items/shaker-2.png'
      },
      { id: 56,
        name: "Golden Reel Guardian Belt",
        category: "Earthshaker",
        description: "Golden Reel Guardian.",
        price: 0.53,
        image: 'assets/images/items/shaker-3.png'
      },
      { id: 57,
        name: "Horns of Deep Magma",
        category: "Earthshaker",
        description: "Эти предметы были созданы в сотрудничестве с Evil Geniuses, которые получают часть прибыли от каждой покупки.",
        price: 0.53,
        image: 'assets/images/items/shaker-4.png'
      }
    ],
    orders: []
  };
};
